routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('products', 'ProductController');
Route::resource('users', 'UserController');
Route::resource('comments', 'CommentController');
Route::resource('orders', 'OrderController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Order;
use App\Role;
use App\Comment;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function roles(){
        return $this->belongsToMany(Role::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');

        if($search)
        {
            $users = User::where('name', 'like', '%' . $search . '%')
                ->get();
        }
        else
        {
            $users = User::all();
        }

        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function store(Request $request)
    {
        $name = $request->input('name');
        $email = $request->input('email');
        $password = $request->input('password');
        $admin = $request->input('admin');
        $solde = $request->input('solde');



        $user = new User;
 
        $user->name = $name;
        $user->email = $email;
        $user->password = $password;
        $user->admin = $admin;
        $user->solde = $solde;
        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {


        $name = $request->input('name');
        $email = $request->input('email');
        $password = $request->input('password');
        $admin = $request->input('admin');
        $solde = $request->input('solde');


        $user = User::find($user->id);
        
        if(isset($name))
        {
            $user->name = $name;
        }
        
        if(isset($email))
        {
            $user->email = $email;
        }

        if(isset($password))
        {
            $user->password = $password;
        }

        if(isset($admin))
        {
            $user->admin = $admin;
        }
        
        if(isset($solde))
        {
            $user->solde = $solde;
        }
        $user->save();

        return redirect()->route('users.show',$user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user = User::find($user->id);
        $user->delete();
        
        return redirect()->route('users.index');
    }
}

resources/views/users/create.blade.php
@extends('layouts.template')

@section('Titre')
    Creation :
@endsection

@section('contain')
@if (Auth::user()->admin)
<div class="container">
    <div class="row">
        <div class="card" style="margin: 0 auto;float: none;margin-bottom: 10px;padding:10px">
            <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="name">Nom:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="name" id="name" required="required"><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="email">Email :</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="email" id="email" required="required" ><br><br>
                    </div>
                </div>
                    <div class="row">
                        <div class="col-3">
                            <label style="font-size:1vw;" for="admin">Admin :</label>
                        </div>
                        <div class="col-6">
                            <input style="font-size:1vw;" type="text" name="admin" id="admin" required="required"><br><br>
                        </div>

                        <div class="col-3">
                            <label style="font-size:1vw;" for="solde"> Wallet :</label>
                        </div>
                        <div class="col-6">
                            <input style="font-size:1vw;" type="text" name="solde" id="solde" required="required"><br><br>
                        </div>
                    </div>
                <input style="font-size:1vw;" type="submit" value="Ajouter" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
    
@endif

@if (!Auth::user()->admin)
    <p> Seul les administrateurs ont accès à cette page !</p>
    <div class="col-3">
        <a href="{{ route('products.index') }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-secondary">Retour</a>
    </div>
@endif
@endsection

resources/views/users/edit.blade.php
@extends('layouts.template')

@section('Titre')
    Modifier :
@endsection

@section('contain')
<div class="container">
    <div class="row">
        <div class="card" style="margin: 0 auto;float: none;margin-bottom: 10px;padding:10px">
            <form method="POST" action="{{ route('users.update', $user) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="name">Nom :</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="name" id="name" required="required" value="{{ $user->name }}"><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="description">Email :</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="email" id="email" required="required" value="{{ $user->email }}"> </textarea><br><br>
                    </div>
                </div>

                @if (Auth::user()->admin)
                    <div class="row">
                        <div class="col-3">
                            <label style="font-size:1vw;" for="admin">Admin :</label>
                        </div>
                        <div class="col-6">
                            <input style="font-size:1vw;" type="text" name="admin" id="admin" required="required" value="{{ $user->admin }}"><br><br>
                        </div>

                        <div class="col-3">
                            <label style="font-size:1vw;" for="solde"> Wallet :</label>
                        </div>
                        <div class="col-6">
                            <input style="font-size:1vw;" type="text" name="solde" id="solde" required="required" value="{{ $user->solde }}"><br><br>
                        </div>
                    </div>
                @endif
                <input style="font-size:1vw;" type="submit" value="Edit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts/template')

@section('Titre')
    Users :
@endsection

@section('contain')
@if (Auth::user()->admin)
<div class="container">
    <table class="table table-bordered">

        @foreach ($users as $user) 
            <tr style="width: 18rem;">
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->admin }}</td>
                <td>{{ $user->solde }}</td>
                <td><a class="btn btn-primary" href="{{ route('users.show', $user) }}" class="btn btn-primary">Détails</a></td>
                <td><a class="btn btn-primary" href="{{ route('users.edit', $user) }}" class="btn btn-primary">Edit</a></td>
                <td><form action="{{ route('users.destroy', $user) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button style="width:80%;padding:unset;font-size:1vw;height:1.5vw" type="submit" class="btn btn-danger">Delete</button>
                </form></td>
            </tr>
        @endforeach

    </table>
</div>
@endif
@if (!Auth::user()->admin)
    <p> Seul les administrateurs ont accès à cette page !</p>
    <div class="col-3">
        <a href="{{ route('products.index') }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-secondary">Retour</a>
    </div>
@endif
@endsection

resources/views/users/show.blade.php
@extends('layouts.template')

@section('Titre')
    <p style="text-align:center">Compte</p>
@endsection

@section('contain')
<div class="container">
    <div class="row">
        <div class="col-9" style="border:groove; padding-bottom:0.5vw">
            <div class="row">
                <p style="text-align:center;width:100%;font-size:2vw">{{ $user->name }}</p>
                <p style="text-align:center;width:100%;font-size:2vw">{{ $user->email }}</p>
            </div>
            @if (Auth::user()->admin)
                <div class="row">
                    <p style="width:100%;font-size:2vw">Admin :</p>
                    <p style="width:100%;font-size:1.5vw">{{ $user->admin }}</p>
                </div>
            @endif       
        </div>
        
    </div>
    <div class="row" style="text-align:center">
        <div class="col-3">
            <a href="{{ route('users.index') }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-secondary">Retour</a>
        </div>
        @if (Auth::user()->admin)
            
            <div class="col-3">
                <form action="{{ route('users.destroy', $user) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button style="width:80%;padding:unset;font-size:1vw;height:1.5vw" type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        @endif
        
        <div class="col-6">
                <a href="{{ route('users.edit', $user) }}" style="width:66%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-primary">Modifier</a>
        </div>
    </div>
</div>
<br>
@endsection