routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('products', 'ProductController');
Route::resource('users', 'UserController');
Route::resource('comments', 'CommentController');
Route::resource('orders', 'OrderController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;
use App\Comment;
use Illuminate\Support\Facades\Log;

class Product extends Model
{
    public function comments(){
        return $this -> hasMany(Comment::class);
    }   
    public function orders(){
        return $this->belongsToMany(Order::class);
    }

    public function noter($note)
    {
        $this->nb_note = $this->nb_note + 1;
        $this->total_score = $this->total_score + $note ;
        $this->score = $this->total_score/$this->nb_note;
    }
}
  
    
    

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Traits\UploadTrait;

class ProductController extends Controller
{
    use UploadTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');

        if($search)
        {
            $products = Product::where('gamename', 'like', '%' . $search . '%')
                ->get();
        }
        else
        {
            $products = Product::all();
        }

        return view('products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $img = $request->file('img');
        $gamename = $request->input('gamename');
        $description = $request->input('description');
        $price = $request->input('price');



        $product = new Product;
 
        $product->gamename = $gamename;
        $product->description = $description;
        $product->price = $price;
        $product->save();
        if(isset($img)){
            $repertoire = "/images/";
            $nomImage = $product->id .".".$img->getClientOriginalExtension();
            $chemin = $repertoire . $nomImage;
            $product->image = $nomImage;
            $this->uploadOne($img, $repertoire, 'image', $nomImage);
        }
        $product->save();
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {

        $gamename = $request->input('gamename');
        $description = $request->input('description');
        $price = $request->input('price');

        $image = $request->file('img');

        $vote = $request->input('vote');

        $product = Product::find($product->id);
        if(isset($vote)){
            $product->noter($vote);
        }
        if(isset($gamename))
        {
            $product->gamename = $gamename;
        }

        if(isset($price))
        {
            $product->price = $price;
        }

        if(isset($description))
        {
            $product->description = $description;
        }
        
        
        

        if(isset($image)){
            $repertoire = "/images/";
            $nomImage = $product->id .".".$image->getClientOriginalExtension();
            $chemin = $repertoire . $nomImage;
            $this->uploadOne($image, $repertoire, 'image', $nomImage);
            $product->image = $nomImage;
        }

        $product->save();



        return redirect()->route('products.show',$product);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product = Product::find($product->id);
        $product->delete();
        
        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('layouts.template')

@section('Titre')
    Creation :
@endsection

@section('contain')
@if (Auth::user()->admin)
<div class="container">
    <div class="row">
        <div class="card" style="margin: 0 auto;float: none;margin-bottom: 10px;padding:10px">
            <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="img">Image:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="file" name="img" id="img" required="required"><br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="gamename">Nom:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="gamename" id="gamename" required="required"><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="description">Description:</label>
                    </div>
                    <div class="col-6">
                        <textarea style="font-size:1vw;" rows="4" cols="40" name="description" id="description" required="required" > </textarea><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="price">Prix:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="price" id="price" required="required"><br><br>
                    </div>
                </div>
                <input style="font-size:1vw;" type="submit" value="Ajouter" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
@endif

@if (!Auth::user()->admin)
    <p> Seul les administrateurs ont accès à cette page !</p>
    <div class="col-3">
        <a href="{{ route('products.index') }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-secondary">Retour</a>
    </div>
@endif

@endsection

resources/views/products/edit.blade.php
@extends('layouts.template')

@section('Titre')
    <p style="text-align:center">Modifier</p>
@endsection

@section('contain')
<div class="container">
    <div class="row">
        <div class="card" style="margin: 0 auto;float: none;margin-bottom: 10px;padding:10px">
            <form method="POST" action="{{ route('products.update', $product) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="img">Image:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="file" name="img" id="img"  value="{{ $product->image }}"><br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="gamename">Nom:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="gamename" id="gamename" required="required" value="{{ $product->gamename }}"><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="description">Description:</label>
                    </div>
                    <div class="col-6">
                        <textarea style="font-size:1vw;" rows="4" cols="40" name="description" id="description" required="required" value="{{ $product->description }}"> {{ $product->description }}</textarea><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="price">Prix:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="text" name="price" id="price" required="required" value="{{ $product->price }}"><br><br>
                    </div>
                </div>
                <input style="font-size:1vw;" type="submit" value="Modifier" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts/template')

@section('Title')
    GamePrestige
@endsection

@section('contain')
<div class="container">
    <div class="row">

        @foreach ($products as $product) 
            <div class="card" style="width: 18rem;">
                <img src="/images/{{ $product->image }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{ $product->gamename }}</h5>
                  <p class="card-text">{{ $product->price }}€</p>
                  <a class="btn btn-primary" href="{{ route('products.show', $product) }}" class="btn btn-primary">Détails</a>
                </div>
              </div>
        @endforeach

    </div>
  </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.template')

@section('Titre')
    <p style="text-align:center">Détails</p>
@endsection

@section('contain')
<div class="container">
    <div class="row" style="padding:1vw">
        <div class="col-3">
            <img style="width:100%" src="/images/{{ $product->image }}" alt=""></a>
        </div>
        <div class="col-9" style="border:groove; padding-bottom:0.5vw">
            <div class="row">
                <p style="text-align:center;width:100%;font-size:2vw">{{ $product->gamename }}</p>
            </div>
            <div class="row">
                <p style="width:100%;font-size:2vw">Description :</p>
                <p style="width:100%;font-size:1.5vw">{{ $product->description }}</p>
            </div>
            <div class="row">
                <div class="col-2">
                    <p style="width:100%;font-size:1vw">{{ $product->score }}/5</p>
                </div>
                <div class="col-5">
                    <p style="width:100%;font-size:1vw">Exemplaire vendu : {{ $product->sold }}</p>
                </div>
                <div class="col-5">
                    <form method="POST" action="{{ route('orders.store', ['product_id'=>$product, 'user_id' => Auth::user()->id]) }}">
                        @csrf
                        <input style="font-size:1vw;" type="submit" value="Ajouter au panier : {{ $product->price }}€" class="btn btn-primary" style="width:80%;padding:unset;font-size:1vw;height:1.5vw">
                    </form>
                </div>
            </div>
        </div>
        
    </div>
    <div class="row" style="text-align:center; margin-bottom:1vw">
        <div class="col-3">
            <a href="{{ route('products.index') }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-secondary">Retour</a>
        </div>
        @if (Auth::user()->admin)
            <div class="col-6">
                <a href="{{ route('products.edit', $product) }}" style="width:66%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-primary">Modifier</a>
            </div>
            <div class="col-3">
                <form action="{{ route('products.destroy', $product) }}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button style="width:80%;padding:unset;font-size:1vw;height:1.5vw" type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        @endif
    </div>
    <div class="row" style="text-align:center; margin-bottom:1vw">
        <div class="col-3">
            <a href="{{ route('comments.create',['product' => $product]) }}" style="width:80%;padding:unset;font-size:1vw;height:1.5vw" class="btn btn-primary">Ajouter un commentaire</a>
        </div>
        <div class="col-3">
            <form method="POST" action="{{ route('products.update', $product) }}">
                @method('PUT')
                @csrf
                <div class="row">
                    <div class="col-3">
                        <label style="font-size:1vw;" for="vote">Note:</label>
                    </div>
                    <div class="col-6">
                        <input style="font-size:1vw;" type="number" name="vote" id="vote"  min="0" max="5" required="required" ><br><br>
                    </div>
                </div>
                <input style="font-size:1vw;" type="submit" value="Voter" class="btn btn-primary">
            </form>
        </div>
    </div>
    <p>Liste des commentaires</p>
    <div class="row" style="border:groove;border-bottom:unset">
        @foreach ($product->comments as $comment)
            <div class="row">
                <div class="col-2" style="border-right:groove;border-bottom:groove">
                    <p>Utilisateur : {{ $comment->user->name }}</p>
                </div>
                <div class="col-10" style="border-bottom:groove">
                    <p>{{ $comment->comment }}</p>
                </div>
            </div><br>
        @endforeach
    </div>
</div>
<br>
@endsection