routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('products', 'ProductController');
Route::resource('users', 'UserController');
Route::resource('comments', 'CommentController');
Route::resource('orders', 'OrderController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Product;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class Order extends Model
{
    public function product(){
        return $this->belongsTo(Product::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
    
    public static function order_exist($user_id,$product_id){
        return DB::table('orders')->where('user_id','=',$user_id)->where('product_id','=',$product_id)->where('buyed','<>',1)->get();
    }

    public static function orders_not_buyed($user_id){
        $orders = DB::table('orders')->where('user_id','=',$user_id)->where('buyed','<>',1)->get();
        Log::info($orders);
        return $orders;
    }


}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;


class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $orders = Order::all();


        return view('orders.index', ['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product_id = $request->input('product_id');

        $product = Product::find($product_id);
        $user_id = $request->input('user_id');
        $order = Order::order_exist($user_id,$product_id);

        if(isset($order[0])){
            $order = Order::find($order[0]->id);
            $quantity = $order->quantity + 1;
        }else{    
            $order = new Order;
            $quantity = 1;
        }
        $buy_at = date('Y-m-d');
        $buyed = false;
 
        $order->buy_at = $buy_at;
        $order->quantity = $quantity;
        $order->buyed = $buyed;
        $order->user_id = $user_id;
        $order->product_id = $product_id;

        $order->save();

        return redirect()->route('products.show',$product);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('orders.show', ['order' => $order]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('orders.edit', ['order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {

        $quantity = $request->input('quantity');
        $buyed = $request->input('buyed');

        $orders = Order::all();
        $total = 0;
        foreach($orders as $order){
            if($order->buyed == 0 && $order->user->id == Auth::user()->id){
                $total = $total + ($order->quantity * $order->product->price);
            }
        }
        foreach($orders as $order){
            if($order->buyed == 0 && $order->user->id == Auth::user()->id){
                if(isset($quantity))
                {
                    $order->quantity = $quantity;
                }

                if(isset($buyed) && Auth::user()->solde >= $total)
                {
                    $user = Auth::user();
                    $user-> solde = $user-> solde - $total;
                    Log::info($order);
                    $order->buyed = true;
                    Log::info($order);
                }

                $order->save();
            }
        }
        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(order $order)
    {
        $order = Order::find($order->id);
        $order->delete();
        
        return redirect()->route('orders.index');
    }
}

resources/views/orders/index.blade.php
@extends('layouts.template')

@section('Titre')
    <p style="text-align:center">Liste des articles dans le panier</p>
@endsection

@section('contain')
<div class="container">
    <div class="row">

        @foreach ($orders as $order)
            @if($order->buyed == 0 && $order->user->id == Auth::user()->id)
                <div class="row" style="padding:1vw">
                    <div class="col-1">
                        <img src="/images/{{ $order->product->image }}" alt="" style="width:5vw;height:8vw"></a>
                    </div>
                    <div class="col-3" style="border:groove; padding-bottom:0.5vw">
                        <p style="text-align:center;width:100%;font-size:2vw">{{ $order->product->gamename }}</p>
                        <br>
                        <p style="text-align:center;width:100%;font-size:1vw">{{ $order->product->description }}</p>
                    </div>
                    <div class="col-1" style="border:groove; padding-bottom:0.5vw">
                        <p style="text-align:center;width:100%;font-size:2vw">{{ $order->product->price }} €</p>
                    </div>
                    <div class="col-4" style="border:groove; padding-bottom:0.5vw">
                        <form method="POST" action="{{ route('orders.update', $order) }}">
                            @method('PUT')
                            @csrf
                            <div class="row">
                                <div class="col-6">
                                    <input style="font-size:1vw" type="number" name="quantity" id="quantity" value="{{ $order->quantity}}"  min="0" required="required" ><br><br>
                                </div>
                                <div class="col-6">
                                    <input style="font-size:1vw;" type="submit" value="valider" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-2" style="border:groove; padding-bottom:0.5vw">
                    <form action="{{ route('orders.destroy', $order) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button style="width:80%;padding:unset;font-size:1vw;height:1.5vw" type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    </div>
                </div>
              </div>
            @endif
        @endforeach
    </div>
    <a class="btn btn-primary" href="{{ route('products.index') }}" class="btn btn-primary">Retour</a>
    <form method="POST" action="{{ route('orders.update', $orders[0]) }}">
                @method('PUT')
                @csrf
                <input type="hidden" name="buyed" id="buyed" value="{{$orders[0]}}">
                <input style="font-size:1vw;" type="submit" value="Acheter" name="Acheter" id="Acheter" class="btn btn-primary">
    </form>
</div>
@endsection